### ISSUE TITLE
TouchableNativeFeedback is not supported on this platform

### ISSUE THREAD

**Issue by OdderOwl** [CaptainOmega/react-native-tree-view#1]
I tried to use the example in my project to see how it would look like and copied the example to start. I didnt change anything and i got the following error:

TouchableNativeFeedback is not supported on this platform.

No data is displayed, but the "table" with the headlines and backgroundcolor is displayed.
Im using a MacBook with XCode.
Anyone can help with this?

**Comment by CaptainOmega** [comment]
This issue fixed. Please update "react-native-tree-view" package to version 1.0.2
